version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch1
    environment:
      - cluster.name=test_cluster
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch2
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1_830_tp2bis:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch2
    environment:
      - cluster.name=test_cluster
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch2
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2_830_tp2bis:/usr/share/elasticsearch/data
      
volumes:
  esdata1_830_tp2bis:
    driver: local
  esdata2_830_tp2bis:
    driver: local
